import { type NextPage } from "next";
import Head from "next/head";

import { Shell } from "~/components/Shell";

const Empty: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Shell>
        <div className="flex flex-col gap-8">Nothing to see here, lol.</div>
      </Shell>
    </>
  );
};

export default Empty;
